/**
 * Agenda Template System: Role-based meeting agenda generation
 *
 * 4 meeting types:
 *   1. All-Staff Meeting (50 min), ED, EVP, DOP
 *   2. Team Meeting (35 min), ED, EVP, DOP
 *   3. 1:1 with Direct Report (30 min), ED, EVP, DOP
 *   4. Organization-Wide / Board (60 min), ED, EVP only
 *
 * Each agenda pulls from live data (themes, actions, YSWD, KPIs) and
 * produces a structured, copy-ready document.
 */

import type {
  MeetingType,
  MeetingTypeConfig,
  MeetingAgenda,
  AgendaSection,
  SynthesizedAction,
  ThemeAggregate,
  KPISnapshot,
  YouSaidWeDid,
  UserRole,
} from './types';

// ─── Meeting Type Configurations ──────────────────────────

export const MEETING_TYPES: MeetingTypeConfig[] = [
  {
    type: 'all-staff',
    label: 'All-Staff Meeting',
    description: 'Transparent sharing of survey findings, accountability loop, and action updates with your full team.',
    allowedRoles: ['ed', 'evp', 'dop'],
  },
  {
    type: 'team',
    label: 'Team Meeting',
    description: 'Department-focused discussion of themes, coaching check-in, and action item review.',
    allowedRoles: ['ed', 'evp', 'dop'],
  },
  {
    type: 'one-on-one',
    label: '1:1 with Direct Report',
    description: 'Personal check-in with feedback themes, development conversation, and support needs.',
    allowedRoles: ['ed', 'evp', 'dop'],
  },
  {
    type: 'org-wide',
    label: 'Organization-Wide / Board',
    description: 'Executive summary with KPI review, strategic themes, resource implications, and board-level accountability.',
    allowedRoles: ['ed', 'evp'],
  },
];

// ─── Data Bundle for Agenda Generation ────────────────────

export interface AgendaData {
  actions: SynthesizedAction[];
  themes: ThemeAggregate[];
  kpis: KPISnapshot[];
  youSaidWeDid: YouSaidWeDid[];
  userName: string;
  department?: string;
}

// ─── Public API ───────────────────────────────────────────

/**
 * Get available meeting types for a given role.
 */
export function getMeetingTypesForRole(role: UserRole): MeetingTypeConfig[] {
  return MEETING_TYPES.filter(mt => mt.allowedRoles.includes(role));
}

/**
 * Generate a full meeting agenda from data.
 */
export function generateAgenda(
  meetingType: MeetingType,
  data: AgendaData
): MeetingAgenda {
  const config = MEETING_TYPES.find(mt => mt.type === meetingType);
  if (!config) {
    throw new Error(`Unknown meeting type: ${meetingType}`);
  }

  const now = new Date();
  const base = {
    meetingType,
    title: config.label,
    generatedAt: now.toISOString(),
    preparedBy: data.userName,
  };

  switch (meetingType) {
    case 'all-staff':
      return { ...base, sections: buildAllStaffSections(data) };
    case 'team':
      return { ...base, sections: buildTeamSections(data) };
    case 'one-on-one':
      return { ...base, sections: buildOneOnOneSections(data) };
    case 'org-wide':
      return { ...base, sections: buildOrgWideSections(data) };
    default:
      return { ...base, sections: [] };
  }
}

/**
 * Format agenda as plain text for clipboard / email.
 */
export function formatAgendaAsText(agenda: MeetingAgenda): string {
  const lines: string[] = [];
  const totalMinutes = agenda.sections.reduce((sum, s) => sum + s.durationMinutes, 0);

  lines.push('═'.repeat(52));
  lines.push(agenda.title.toUpperCase());
  lines.push('═'.repeat(52));
  lines.push(`Prepared by: ${agenda.preparedBy}`);
  lines.push(`Date: ${new Date(agenda.generatedAt).toLocaleDateString()}`);
  lines.push(`Total Duration: ${totalMinutes} minutes`);
  lines.push('');

  let runningTime = 0;
  agenda.sections.forEach((section, i) => {
    const startMin = runningTime;
    runningTime += section.durationMinutes;
    lines.push(`─── ${i + 1}. ${section.title} (${section.durationMinutes} min) ───`);
    lines.push(`    ${formatTimeRange(startMin, runningTime)}`);
    lines.push('');

    section.items.forEach(item => {
      lines.push(`    • ${item}`);
    });
    lines.push('');
  });

  lines.push('─'.repeat(52));
  lines.push('Generated by FieldVoices Impact Plan');

  return lines.join('\n');
}

/**
 * Format agenda as Markdown for documents.
 */
export function formatAgendaAsMarkdown(agenda: MeetingAgenda): string {
  const lines: string[] = [];
  const totalMinutes = agenda.sections.reduce((sum, s) => sum + s.durationMinutes, 0);

  lines.push(`# ${agenda.title}`);
  lines.push('');
  lines.push(`**Prepared by:** ${agenda.preparedBy}  `);
  lines.push(`**Date:** ${new Date(agenda.generatedAt).toLocaleDateString()}  `);
  lines.push(`**Total Duration:** ${totalMinutes} minutes`);
  lines.push('');
  lines.push('---');
  lines.push('');

  let runningTime = 0;
  agenda.sections.forEach((section, i) => {
    const startMin = runningTime;
    runningTime += section.durationMinutes;
    lines.push(`## ${i + 1}. ${section.title} *(${section.durationMinutes} min, ${formatTimeRange(startMin, runningTime)})*`);
    lines.push('');

    section.items.forEach(item => {
      lines.push(`- ${item}`);
    });
    lines.push('');
  });

  lines.push('---');
  lines.push('*Generated by FieldVoices Impact Plan*');

  return lines.join('\n');
}

// ─── Template Builders ────────────────────────────────────

/**
 * All-Staff Meeting, 50 minutes
 * Transparent sharing + accountability loop + action updates
 */
function buildAllStaffSections(data: AgendaData): AgendaSection[] {
  const topThemes = data.themes
    .slice()
    .sort((a, b) => b.frequency - a.frequency)
    .slice(0, 3);

  const yswd = data.youSaidWeDid.slice(0, 3);
  const urgentActions = data.actions.filter(a => !a.completed && (a.priority === 'urgent' || a.priority === 'high')).slice(0, 4);
  const completedActions = data.actions.filter(a => a.completed).slice(0, 3);

  return [
    {
      title: 'Opening Check-In',
      durationMinutes: 5,
      type: 'check-in',
      items: [
        'Brief pulse: "One word, how are you arriving today?"',
        'Ground the room: acknowledge the work, name the purpose of this meeting',
        'Reminder: what we share here comes from your voices. This is your space',
      ],
    },
    {
      title: 'Survey Findings Overview',
      durationMinutes: 10,
      type: 'discussion',
      items: [
        `${topThemes.length} top theme${topThemes.length !== 1 ? 's' : ''} from recent surveys:`,
        ...topThemes.map(t => `Theme: "${t.theme}", ${t.frequency} signals, ${t.severity} severity (${t.department})`),
        topThemes.length === 0 ? 'No active themes to review. Surveys pending' : 'Discussion: What resonates? What are we missing?',
      ],
    },
    {
      title: 'You Said / We Did Review',
      durationMinutes: 10,
      type: 'accountability',
      items: yswd.length > 0
        ? [
            'Accountability loop: actions taken in response to your feedback:',
            ...yswd.map(y => `You said: "${y.youSaid}" → We did: ${y.weDid}`),
            'Open floor: Did these changes land? What still needs attention?',
          ]
        : [
            'No You Said / We Did entries to review yet.',
            'Reminder: this space will be used to track actions taken from your feedback.',
          ],
    },
    {
      title: 'Action Items Update',
      durationMinutes: 10,
      type: 'action-review',
      items: [
        ...(urgentActions.length > 0
          ? [
              'Current priority actions:',
              ...urgentActions.map(a => `[${a.priority.toUpperCase()}] ${a.description}, ${a.suggestedTimeline}`),
            ]
          : ['No urgent or high-priority actions at this time.']),
        ...(completedActions.length > 0
          ? [
              '',
              'Recently completed:',
              ...completedActions.map(a => `✓ ${a.description}`),
            ]
          : []),
      ],
    },
    {
      title: 'Open Discussion',
      durationMinutes: 10,
      type: 'discussion',
      items: [
        'What else is on your mind that the surveys didn\'t capture?',
        'Any shout-outs or recognitions?',
        'What support do you need from leadership this week?',
      ],
    },
    {
      title: 'Closing & Next Steps',
      durationMinutes: 5,
      type: 'action-review',
      items: [
        'Summarize commitments made in this meeting',
        'Confirm next meeting date and any interim check-ins',
        'Closing thought: "What\'s one thing you\'re taking away from today?"',
      ],
    },
  ];
}

/**
 * Team Meeting, 35 minutes
 * Department-focused themes + coaching + actions
 */
function buildTeamSections(data: AgendaData): AgendaSection[] {
  const deptThemes = data.department
    ? data.themes.filter(t => t.department === data.department).slice(0, 3)
    : data.themes.slice(0, 3);

  const teamActions = data.actions.filter(a => !a.completed).slice(0, 3);

  return [
    {
      title: 'Team Check-In',
      durationMinutes: 5,
      type: 'check-in',
      items: [
        'Quick round: "What\'s one win and one challenge from this week?"',
        'Acknowledge the team\'s effort and set the meeting tone',
      ],
    },
    {
      title: 'Department Themes',
      durationMinutes: 10,
      type: 'discussion',
      items: deptThemes.length > 0
        ? [
            'Themes from our team\'s survey responses:',
            ...deptThemes.map(t => `"${t.theme}", ${t.frequency} signals, ${t.severity} severity`),
            'Discussion: Are these accurate? What context are we missing?',
          ]
        : [
            'No department-specific themes surfaced yet.',
            'Discussion: What\'s on the team\'s mind that we should track?',
          ],
    },
    {
      title: 'Action Items Review',
      durationMinutes: 10,
      type: 'action-review',
      items: teamActions.length > 0
        ? [
            'Current action items for our team:',
            ...teamActions.map(a => `[${a.priority.toUpperCase()}] ${a.description}, ${a.suggestedTimeline}`),
            'Status check: Who owns what? What\'s blocked?',
          ]
        : [
            'No active action items to review.',
            'Use this time to identify emerging needs or revisit past commitments.',
          ],
    },
    {
      title: 'Coaching Check-In',
      durationMinutes: 5,
      type: 'check-in',
      items: [
        'How are coaching sessions going? Any scheduling conflicts?',
        'Is anyone needing additional support or mentorship?',
        'Reminder: coaching blocks are protected time. Honor them',
      ],
    },
    {
      title: 'Next Steps',
      durationMinutes: 5,
      type: 'action-review',
      items: [
        'Capture new action items from this discussion',
        'Assign owners and timelines',
        'Confirm next team meeting date',
      ],
    },
  ];
}

/**
 * 1:1 with Direct Report, 30 minutes
 * Personal, developmental, supportive
 */
function buildOneOnOneSections(data: AgendaData): AgendaSection[] {
  const topThemes = data.themes.slice(0, 2);
  const relevantActions = data.actions.filter(a => !a.completed).slice(0, 2);

  return [
    {
      title: 'Personal Check-In',
      durationMinutes: 5,
      type: 'check-in',
      items: [
        'How are you doing, genuinely?',
        'Anything happening outside of work that\'s affecting your energy or focus?',
        'This is a safe space for honest conversation.',
      ],
    },
    {
      title: 'Feedback Themes from Their Area',
      durationMinutes: 10,
      type: 'discussion',
      items: topThemes.length > 0
        ? [
            'Here\'s what we\'re hearing from the team in your area:',
            ...topThemes.map(t => `"${t.theme}", ${t.frequency} signals, ${t.severity} severity`),
            'What\'s your read on this? Is this matching what you see day-to-day?',
            'What would help address this from your perspective?',
          ]
        : [
            'No specific themes to discuss from recent surveys.',
            'What are you observing that the data might not be capturing?',
          ],
    },
    {
      title: 'Development Conversation',
      durationMinutes: 5,
      type: 'strategic',
      items: [
        'What skills or experiences do you want to grow this quarter?',
        'Is there a project or responsibility you\'d like to take on?',
        'How can I support your professional development?',
      ],
    },
    {
      title: 'Support Needs',
      durationMinutes: 5,
      type: 'check-in',
      items: [
        'What\'s making your work harder than it needs to be?',
        'What resources, tools, or permissions would help?',
        'Is there anything you need from me that you\'re not getting?',
      ],
    },
    {
      title: 'Action Items & Follow-Up',
      durationMinutes: 5,
      type: 'action-review',
      items: [
        ...(relevantActions.length > 0
          ? [
              'Current items relevant to your area:',
              ...relevantActions.map(a => `[${a.priority.toUpperCase()}] ${a.description}`),
            ]
          : []),
        'Capture any new commitments from this conversation',
        'Confirm next 1:1 date and any interim follow-ups',
      ],
    },
  ];
}

/**
 * Organization-Wide / Board, 60 minutes
 * Executive summary, KPIs, strategic themes, resource implications
 */
function buildOrgWideSections(data: AgendaData): AgendaSection[] {
  const allThemes = data.themes.slice().sort((a, b) => b.frequency - a.frequency).slice(0, 5);
  const yswd = data.youSaidWeDid.slice(0, 4);
  const urgentActions = data.actions.filter(a => !a.completed && (a.priority === 'urgent' || a.priority === 'high')).slice(0, 5);

  // KPI categorization
  const concerningKPIs = data.kpis.filter(k => {
    const isNegativeMetric = k.label.toLowerCase().includes('duplicate') || k.label.toLowerCase().includes('friction');
    return isNegativeMetric ? k.trend === 'up' : k.trend === 'down';
  });
  const positiveKPIs = data.kpis.filter(k => {
    const isNegativeMetric = k.label.toLowerCase().includes('duplicate') || k.label.toLowerCase().includes('friction');
    return isNegativeMetric ? k.trend === 'down' : k.trend === 'up';
  });

  return [
    {
      title: 'Executive Summary',
      durationMinutes: 5,
      type: 'strategic',
      items: [
        `${data.themes.length} active theme${data.themes.length !== 1 ? 's' : ''} across the organization`,
        `${data.actions.filter(a => !a.completed).length} open action items (${urgentActions.length} urgent/high)`,
        `${yswd.length} accountability loop${yswd.length !== 1 ? 's' : ''} closed (You Said / We Did)`,
        `${data.kpis.length} KPIs tracked: ${positiveKPIs.length} trending positive, ${concerningKPIs.length} requiring attention`,
      ],
    },
    {
      title: 'KPI Dashboard Review',
      durationMinutes: 10,
      type: 'discussion',
      items: [
        'Full metrics overview:',
        ...data.kpis.map(k => `${k.label}: ${k.value} (trending ${k.trend})`),
        ...(concerningKPIs.length > 0
          ? ['', 'Attention needed:', ...concerningKPIs.map(k => `⚠ ${k.label}: ${k.value}`)]
          : []),
      ],
    },
    {
      title: 'Strategic Themes',
      durationMinutes: 15,
      type: 'discussion',
      items: allThemes.length > 0
        ? [
            'Top themes across the organization:',
            ...allThemes.map(t => `"${t.theme}", ${t.frequency} signals, ${t.severity} severity (${t.department})`),
            '',
            'Discussion: Which of these require board-level attention or resource allocation?',
          ]
        : ['No active themes. Surveys pending.'],
    },
    {
      title: 'You Said / We Did Accountability',
      durationMinutes: 10,
      type: 'accountability',
      items: yswd.length > 0
        ? [
            'Actions taken in response to staff and community feedback:',
            ...yswd.map(y => `"${y.youSaid}" → ${y.weDid} (${y.department}, resolved ${y.resolvedDate})`),
            '',
            'Board review: Are these responses adequate? What follow-up is needed?',
          ]
        : ['No accountability loop entries to review.'],
    },
    {
      title: 'Resource & Budget Implications',
      durationMinutes: 10,
      type: 'strategic',
      items: [
        'Based on current themes and actions, the following may require resource allocation:',
        ...(urgentActions.length > 0
          ? urgentActions.map(a => `[${a.priority.toUpperCase()}] ${a.description}, ${a.category} (${a.suggestedTimeline})`)
          : ['No resource-intensive actions at this time.']),
        '',
        'Discussion: Budget implications? Staffing needs? Timeline adjustments?',
      ],
    },
    {
      title: 'Strategic Initiatives & Next Steps',
      durationMinutes: 10,
      type: 'action-review',
      items: [
        'Summarize decisions made in this meeting',
        'Identify items requiring board vote or formal approval',
        'Assign executive owners for follow-up items',
        'Confirm next organization-wide meeting date',
        'Schedule any interim leadership check-ins as needed',
      ],
    },
  ];
}

// ─── Helpers ──────────────────────────────────────────────

function formatTimeRange(startMin: number, endMin: number): string {
  const fmtMin = (m: number) => {
    const h = Math.floor(m / 60);
    const min = m % 60;
    return `${h}:${min.toString().padStart(2, '0')}`;
  };
  return `${fmtMin(startMin)} – ${fmtMin(endMin)}`;
}
